# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env.production
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
  
  redis:
    image: redis:7-alpine

volumes:
  mongo_data: